package com.exen.example.domain.constant;

public enum Code {
    REQUEST_VALIDATION_ERROR,
    NICKNAME_TAKEN,
    INTERNAL_SERVER_ERROR,
    TEST,
    AUTHORIZATION_ERROR,
    MISSING_REQUEST_HEADER,
    NOT_READABLE,
    SUBSCRIPTION_LOGIC_ERROR,
    ALREADY_SUBSCRIBED,
    PUBLISHER_NOT_FOUND,
    ARGUMENT_TYPE_MISMATCH,
    USER_NOT_FOUND
}
